services:
  mysql-container:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root123456'
      MYSQL_DATABASE: 'eazy_admin'
      MYSQL_USER: 'eazy_admin_dev'
      MYSQL_PASSWORD: 'dev123456'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  # 运行测试的时候连接的数据库
  mysql-test-container:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root123456'
      MYSQL_DATABASE: 'eazy_admin'
      MYSQL_USER: 'eazy_admin_dev'
      MYSQL_PASSWORD: 'dev123456'
    ports:
      - '13306:3306'
    volumes:
      - mysql-test-data:/var/lib/mysql

  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
  mysql-test-data:
